name: Terraform checks

on:
  push:
    branches:
      - "**"
    paths:
      - "terraform/**"

permissions:
  contents: read
  id-token: write

defaults:
  run:
    working-directory: terraform

jobs:
  validate:
    if: github.actor == 'trngnneee'
    name: Format and validate
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Check formatting
        run: terraform fmt -check -recursive

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Initialize Terraform
        run: terraform init -input=false

      - name: Validate Terraform configuration
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false