name: Terraform checks

on:
  push:
    branches:
      - "**"
    paths:
      - "terraform/**"

permissions:
  contents: read

defaults:
  run:
    working-directory: terraform

jobs:
  validate:
    if: github.actor == 'trngnneee'
    name: Format and validate
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Check formatting
        run: terraform fmt -check -recursive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Initialize Terraform
        run: terraform init -backend=false -input=false

      - name: Validate Terraform configuration
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false